//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentInfoManagmentSystem.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public int MajorClassId { get; set; }
        public Nullable<int> Age { get; set; }
        public string Sex { get; set; }
    
        public virtual MajorClass MajorClass { get; set; }
    }
}
